// THIS FILE IS AUTOGENERATED, DO NOT EDIT
// Generated by mify
// vim: set ft=go:

package main

import (
	"context"
	"example.com/namespace/todo-app/go-services/internal/todo-backend/generated/app"
)

func main() {
	app := app.NewMifyServiceApp(context.Background())
	app.Run()
}
